version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: shiro-wallet_shiro-frontend_1
      APP_PORT: 3000
  
  web:
    image: ghcr.io/diamondhands-dev/shiro-frontend:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
        API_ROOT: http://localhost:3333
  # If your app has more services, like a database container, you can define those
  # services below:
  # db:
  #   image: <docker-image>:<tag>
  #   ...
  backend:
    image: ghcr.io/diamondhands-dev/shiro-backend:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3333:8080
    volumes:
      - ${APP_DATA_DIR}/tmp/shiro-wallet:/tmp/shiro-wallet
    environment:
        BITCOIN_NETWORK: testnet