version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shiro-wallet_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/diamondhands-dev/shiro-frontend:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
        API_ROOT: http://shiro.diamondhands.technology:8080
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - ${APP_DATA_DIR}/tmp/shiro-wallet:/tmp/shiro-wallet
