version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shiro-wallet_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/diamondhands-dev/shiro-frontend:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
        BITCOIN_NETWORK_NAME: testnet
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - /tmp/shiro-wallet:/tmp/shiro-wallet
      # This does not work since Wallet can't lock the db file somehow.
      #- ${APP_DATA_DIR}/tmp/shiro-wallet:/tmp/shiro-wallet
